#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1507357782                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/ios-marketing.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Ringtones Maker                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Are you bored by the default ringtones you have on your iPhone?
                                            You are looking for unique cell phone ringtones with your own style
                                            With best ringtone maker you can create and custom new ringtone for your self
                                            This application is a free that enables you to cut mp3 and other audio files and make ringtones on your iPhone device fast and easy.



enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Le Do                                
your_link                                 : http://proxteam.github.io/ringtone
your_city                                 : HaNoi                                
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Discover  
    description                           : The most popular ringtones
    fontawesome_icon_name                 : magic

  - title                                 : Ringtone Maker
    description                           : Scan music stored in your phone and various audio files, music editing and clipping
    fontawesome_icon_name                 : calendar-check

  - title                                 : Make unique ringtone
    description                           : Record ringtone use songs & karaoke video from youtube with professional audio and video effects
    fontawesome_icon_name                 : location-arrow

  - title                                 : Wallpaper
    description                           : Great wallpaper there if you needed
    fontawesome_icon_name                 : link
  
  - title                                 : #Feature List
    description                           : #Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #star

  - title                                 : Contact
    description                           : 'Messenger: <a href="https://m.me/416305462459391">me</a><br>Email: <a href="mailto:appfeedback118@yandex.com">appfeedback118</a>'
    fontawesome_icon_name                 : address-card

  - title                                 : Privacy & Term of service
    description                           : <a href="https://proxteam.github.io/privacy.htm">Privacy</a><br><a href="https://proxteam.github.io/term">Term of service</a>
    fontawesome_icon_name                 : user-shield



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
